"use client";

import { DocHero, DocSection, CodeBlock, InfoBox } from "../../../components/docs/DocComponents";
import { motion } from "framer-motion";
import { CodeIcon, LightningBoltIcon, MixIcon } from "@radix-ui/react-icons";

export default function RecipesPage() {
    return (
        <article className="prose prose-invert max-w-none">
            <DocHero
                title="Standard Recipes"
                subtitle="The declarative logic layer of the TaaS network. Recipes define the Sovereign Logic required to attest to structured reality."
            />

            <DocSection title="What is a Recipe?">
                <p>
                    A Recipe is a deterministic Sovereign Logic definition that tells the TaaS network how to resolve a specific truth.
                    It is the "instruction set" for Sentinel nodes to execute within their sandboxed, verifiable environment.
                </p>

                <div className="my-16 p-12 rounded-3xl bg-muted/10 border border-border relative overflow-hidden group">
                    <div className="absolute inset-0 bg-grid-white opacity-[0.02] pointer-events-none" />
                    <RecipeFlowDiagram />
                </div>
            </DocSection>

            <DocSection title="Basic Anatomy">
                <p>A standard Recipe consists of an ID, version, outcome type, and a handler function:</p>
                <CodeBlock
                    language="typescript"
                    code={`import { Recipe, Outcomes } from '@friehub/recipes';\n\nexport const BtcPriceRecipe: Recipe = {\n  id: 'btc-price-usd',\n  version: '1.0.0',\n  outcomeType: 'SCALAR',\n  \n  handler: async ({ feeds }) => {\n    const data = await feeds.fetch('https://api.binance.com/v3/ticker/price?symbol=BTCUSDT');\n    return Outcomes.scalar(data.price, { unit: 'USD' });\n  }\n};`}
                />
            </DocSection>

            <DocSection title="Rich Outcome Types">
                <p>TaaS supports 5 standardized outcome types to handle any level of complex reality:</p>
                <div className="space-y-6 my-10">
                    <OutcomeTypeItem
                        title="Binary"
                        desc="YES/NO results for simple events or logic checks."
                    />
                    <OutcomeTypeItem
                        title="Scalar"
                        desc="Numerical values with units and precision (e.g., Price, Temperature)."
                    />
                    <OutcomeTypeItem
                        title="Categorical"
                        desc="Selection from a fixed list of options (e.g., Winner of a match)."
                    />
                    <OutcomeTypeItem
                        title="Probabilistic"
                        desc="Weighted likelihoods, often generated by AI analysis (0-1 range)."
                    />
                    <OutcomeTypeItem
                        title="Invalid"
                        desc="Used to identify false premises or non-concluded events."
                    />
                </div>
            </DocSection>

            <DocSection title="Best Practices">
                <InfoBox type="important">
                    <strong>Determinism is Mandatory.</strong> Every node in the network must execute the same Recipe and reach the same result. Avoid using non-deterministic functions like <code>Math.random()</code> or <code>Date.now()</code>.
                </InfoBox>
                <p>
                    Always use the provided <code>feeds</code> and <code>utils</code> within the context to ensure your Recipe remains verifiable across the global network.
                </p>
            </DocSection>
        </article>
    );
}

function RecipeFlowDiagram() {
    return (
        <div className="relative flex flex-col md:flex-row items-center justify-between gap-8 py-10 z-10">
            <DiagramNode icon={<MixIcon />} label="Raw Input" />
            <motion.div
                animate={{ x: [0, 10, 0] }}
                transition={{ duration: 2, repeat: Infinity }}
                className="text-primary/40"
            >
                <LightningBoltIcon />
            </motion.div>
            <DiagramNode icon={<CodeIcon />} label="Recipe Logic" active />
            <motion.div
                animate={{ x: [0, 10, 0] }}
                transition={{ duration: 2, repeat: Infinity, delay: 0.5 }}
                className="text-primary/40"
            >
                <LightningBoltIcon />
            </motion.div>
            <DiagramNode icon={<LightningBoltIcon />} label="Attestation" />
        </div>
    );
}

function DiagramNode({ icon, label, active }: { icon: any, label: string, active?: boolean }) {
    return (
        <div className="flex flex-col items-center gap-4">
            <div className={clsx(
                "w-16 h-16 rounded-2xl border flex items-center justify-center transition-all duration-500",
                active
                    ? "bg-primary/10 border-primary text-primary shadow-[0_0_30px_rgba(170,255,184,0.2)]"
                    : "bg-background border-border text-foreground/20"
            )}>
                {icon}
            </div>
            <span className={clsx(
                "text-[10px] font-black uppercase tracking-widest",
                active ? "text-primary" : "text-foreground/20"
            )}>{label}</span>
        </div>
    );
}

function OutcomeTypeItem({ title, desc }: { title: string, desc: string }) {
    return (
        <div className="flex gap-6 items-start p-6 rounded-2xl border border-border bg-muted/10">
            <div className="text-primary mt-1">
                <LightningBoltIcon />
            </div>
            <div>
                <h4 className="text-sm font-bold text-foreground mb-1 uppercase tracking-widest">{title}</h4>
                <p className="text-sm text-foreground/40 leading-relaxed font-light">{desc}</p>
            </div>
        </div>
    );
}
